victoria:
    redis: 'victoria'
    printers:
        - main:
            type: "static"
            address: "192.168.8.8"
            port: 9100
            format: "40x60"
            redis: "victoria"
