despinassy:
    uri: "postgresql://postgres@localhost/sprtch"

victoria:
    redis: 'victoria'
    printers:
        - main:
            type: "static"
            address: "192.168.8.8"
            port: 9100
            width: 150
            height: 100
            dialect: "zpl"
            redis: "victoria"
