victoria:
    name: "victoria"
    publisher:
      type: "redis"
      channel: "victoria-out"
    printers:
        - name: "main"
          printer:
            type: "static"
            address: "192.168.8.8"
            port: 9100
          template:
            dialect: "zpl"
            width: 100
            height: 150
          reader:
            type: "redis"
            channel: "victoria"
