victoria:
    redis: 'victoria'
    printers:
        - name: "main"
          printer:
            type: "stdout"
          template:
            dialect: "json"
            width: 100
            height: 150
          reader:
            type: "stdin"
        - name: "warehouse"
          printer:
            type: "stdout"
          template:
            dialect: "json"
            width: 90
            height: 150
          reader:
            type: "redis"
            redis: "victoria"
